quarkus.http.host=0.0.0.0
%prod.quarkus.http.ssl-port=${PORT:9444}
%prod.quarkus.http.insecure-requests=disabled
%prod.quarkus.http.ssl.certificate.key-store-file=${TLS_KEYSTORE:../tls/server.p12}
%prod.quarkus.http.ssl.certificate.key-store-file-type=PKCS12
%prod.quarkus.http.ssl.certificate.key-store-password=${TLS_KEYSTORE_PASSWORD:changeit}
quarkus.package.jar.type=uber-jar
organization-service.url=${ORGANIZATION_SERVICE_URL:https://localhost:9443}
