quarkus.http.host=0.0.0.0
%prod.quarkus.http.ssl-port=${PORT:9443}
%prod.quarkus.http.insecure-requests=disabled
%prod.quarkus.http.ssl.certificate.key-store-file=${TLS_KEYSTORE:../tls/server.p12}
%prod.quarkus.http.ssl.certificate.key-store-file-type=PKCS12
%prod.quarkus.http.ssl.certificate.key-store-password=${TLS_KEYSTORE_PASSWORD:changeit}
quarkus.package.jar.type=uber-jar
quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=soa
%dev.quarkus.datasource.password=soa-local
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/soa?currentSchema=s389491
%dev.quarkus.datasource.devservices.enabled=false
%prod.quarkus.datasource.username=${DB_USER:soa}
%prod.quarkus.datasource.password=${DB_PASSWORD:soa-local}
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/soa?currentSchema=s389491}
quarkus.hibernate-orm.database.default-schema=s389491
quarkus.hibernate-orm.database.generation=update
%test.quarkus.datasource.devservices.username=soa
%test.quarkus.datasource.devservices.password=soa-test
%test.quarkus.datasource.devservices.db-name=soa
%test.quarkus.datasource.devservices.init-script-path=db/schema.sql
